// 1.總銷售金額
EVALUATE
ROW("Total Sales",
SUM(Sales[Sales fact]))

// 2.總銷售計畫
EVALUATE
ROW("Total Plan",
SUM(Sales[Sales plan]))

// 3.銷售達成率
EVALUATE
ROW("Sales Achievement %",
DIVIDE(SUM(Sales[Sales fact]),SUM(Sales[Sales plan])))

// 4.每個 Manager 的總銷售
EVALUATE
SUMX(VALUES(Sales[Manager]),Sales[Sales fact])


EVALUATE
SUMX(Sales,Sales[Sales fact])

EVALUATE
all(Sales)